#!/usr/bin/expect -f
# arg0:user arg1:presentPasswd arg2:FuturePasswd
set force_conservative 1 ;# set to 1 to force conservative mode even if
;# script wasn't run conservatively originally
if {$force_conservative} {
set send_slow {1 .001}
proc send {ignore arg} {
sleep .1
exp_send -s -- $arg
}
}
#################################################################
#
spawn passwd [ lindex $argv 0]
expect "(actual) contraseña de UNIX:"
send -- "[ lindex $argv 1]\r"
expect "Introduzca la nueva contraseña de UNIX:"
send -- "[ lindex $argv 2]\r"
expect "Vuelva a escribir la nueva contraseña de UNIX:"
send -- "[ lindex $argv 2]\r"
expect eof
exit
